#!/usr/bin/env bash
set -e
#
# Skip, if we are not in "configure" state
#
if [ "$1" != "configure" ]; then
        echo "I: Skipping configuration"
        exit 0
fi

useradd c3su
# Automatically added by dh_installinit/12
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/c3sed" ]; then
		update-rc.d c3sed defaults >/dev/null
		invoke-rc.d c3sed start || exit 1
	fi
fi
# End automatically added section
