#! /bin/sh
#
#		Server by Ereb <https://github.com/ereb-thanatos>
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>
#		Modified for Debian by Ian Murdock <imurdock@gnu.ai.mit.edu>
#       Daemon modified by Zhukov Vitaliy <dragonzx@soclan.ru>

### BEGIN INIT INFO
# Provides:          pvpgn
# Required-Start:    $local_fs $remote_fs $syslog $network $time
# Required-Stop:     $local_fs $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Gaming server that emulates Cossacks 3
# Description: control bnetd daemon
### END INIT INFO

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/cossacks3-server
PIDFILE=/var/run/c3sed.pid
NAME=c3sed
DESC="Cossacks 3 Server Emulator daemon"
USER=c3su

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

case "$1" in
  start)
	echo -n "Starting $DESC: "
	start-stop-daemon --start --quiet --user $USER --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo --exec $DAEMON
	echo "$NAME."
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|status|force-reload}" >&2
	exit 1
	;;
esac

exit 0
